/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTranslateRouteImport } from './routes/api/translate'
import { Route as ApiSummarizeRouteImport } from './routes/api/summarize'
import { Route as ApiScanRouteImport } from './routes/api/scan'
import { Route as ApiExplainRouteImport } from './routes/api/explain'
import { Route as ApiDiagramRouteImport } from './routes/api/diagram'
import { Route as NotesNewIndexRouteImport } from './routes/notes/new/index'
import { Route as NotesIdEditIndexRouteImport } from './routes/notes/$id/edit/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranslateRoute = ApiTranslateRouteImport.update({
  id: '/api/translate',
  path: '/api/translate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSummarizeRoute = ApiSummarizeRouteImport.update({
  id: '/api/summarize',
  path: '/api/summarize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScanRoute = ApiScanRouteImport.update({
  id: '/api/scan',
  path: '/api/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExplainRoute = ApiExplainRouteImport.update({
  id: '/api/explain',
  path: '/api/explain',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDiagramRoute = ApiDiagramRouteImport.update({
  id: '/api/diagram',
  path: '/api/diagram',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesNewIndexRoute = NotesNewIndexRouteImport.update({
  id: '/notes/new/',
  path: '/notes/new/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesIdEditIndexRoute = NotesIdEditIndexRouteImport.update({
  id: '/notes/$id/edit/',
  path: '/notes/$id/edit/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/diagram': typeof ApiDiagramRoute
  '/api/explain': typeof ApiExplainRoute
  '/api/scan': typeof ApiScanRoute
  '/api/summarize': typeof ApiSummarizeRoute
  '/api/translate': typeof ApiTranslateRoute
  '/notes/new/': typeof NotesNewIndexRoute
  '/notes/$id/edit/': typeof NotesIdEditIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/diagram': typeof ApiDiagramRoute
  '/api/explain': typeof ApiExplainRoute
  '/api/scan': typeof ApiScanRoute
  '/api/summarize': typeof ApiSummarizeRoute
  '/api/translate': typeof ApiTranslateRoute
  '/notes/new': typeof NotesNewIndexRoute
  '/notes/$id/edit': typeof NotesIdEditIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/diagram': typeof ApiDiagramRoute
  '/api/explain': typeof ApiExplainRoute
  '/api/scan': typeof ApiScanRoute
  '/api/summarize': typeof ApiSummarizeRoute
  '/api/translate': typeof ApiTranslateRoute
  '/notes/new/': typeof NotesNewIndexRoute
  '/notes/$id/edit/': typeof NotesIdEditIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/diagram'
    | '/api/explain'
    | '/api/scan'
    | '/api/summarize'
    | '/api/translate'
    | '/notes/new/'
    | '/notes/$id/edit/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/diagram'
    | '/api/explain'
    | '/api/scan'
    | '/api/summarize'
    | '/api/translate'
    | '/notes/new'
    | '/notes/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/api/diagram'
    | '/api/explain'
    | '/api/scan'
    | '/api/summarize'
    | '/api/translate'
    | '/notes/new/'
    | '/notes/$id/edit/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiDiagramRoute: typeof ApiDiagramRoute
  ApiExplainRoute: typeof ApiExplainRoute
  ApiScanRoute: typeof ApiScanRoute
  ApiSummarizeRoute: typeof ApiSummarizeRoute
  ApiTranslateRoute: typeof ApiTranslateRoute
  NotesNewIndexRoute: typeof NotesNewIndexRoute
  NotesIdEditIndexRoute: typeof NotesIdEditIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/translate': {
      id: '/api/translate'
      path: '/api/translate'
      fullPath: '/api/translate'
      preLoaderRoute: typeof ApiTranslateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/summarize': {
      id: '/api/summarize'
      path: '/api/summarize'
      fullPath: '/api/summarize'
      preLoaderRoute: typeof ApiSummarizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scan': {
      id: '/api/scan'
      path: '/api/scan'
      fullPath: '/api/scan'
      preLoaderRoute: typeof ApiScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/explain': {
      id: '/api/explain'
      path: '/api/explain'
      fullPath: '/api/explain'
      preLoaderRoute: typeof ApiExplainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/diagram': {
      id: '/api/diagram'
      path: '/api/diagram'
      fullPath: '/api/diagram'
      preLoaderRoute: typeof ApiDiagramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/new/': {
      id: '/notes/new/'
      path: '/notes/new'
      fullPath: '/notes/new/'
      preLoaderRoute: typeof NotesNewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes/$id/edit/': {
      id: '/notes/$id/edit/'
      path: '/notes/$id/edit'
      fullPath: '/notes/$id/edit/'
      preLoaderRoute: typeof NotesIdEditIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiDiagramRoute: ApiDiagramRoute,
  ApiExplainRoute: ApiExplainRoute,
  ApiScanRoute: ApiScanRoute,
  ApiSummarizeRoute: ApiSummarizeRoute,
  ApiTranslateRoute: ApiTranslateRoute,
  NotesNewIndexRoute: NotesNewIndexRoute,
  NotesIdEditIndexRoute: NotesIdEditIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
